### ISSUE TITLE
NPE on startup when creating input descriptions

### ISSUE THREAD

**Issue by oniatus** [Terasology/WorkstationCrafting#3] opened 2016-12-16 10:43 UTC
Tested from the latest engine develop branch and fetched the module today:
Used core gameplay, disabled all modules and activated WorkstationCrafting.
Startup produces this exception:
```
11:38:24.493 [main] ERROR o.t.e.event.internal.EventSystemImpl - Failed to invoke event
java.lang.NullPointerException: null
	at org.terasology.workstation.process.inventory.InventoryProcessPartUtils.createItems(InventoryProcessPartUtils.java:62)
	at org.terasology.workstation.process.inventory.InventoryInputProcessPartCommonSystem.getInputDescriptions(InventoryInputProcessPartCommonSystem.java:171)
	at org.terasology.workstation.process.inventory.InventoryInputProcessPartCommonSystemMethodAccess.invoke(Unknown Source)
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:506)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendStandardEvent(EventSystemImpl.java:269)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:260)
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:145)
	at org.terasology.workstationCrafting.system.CraftingWorkstationProcess.getInputDescriptions(CraftingWorkstationProcess.java:183)
	at org.terasology.workstationInGameHelp.systems.WorkstationItemsInGameHelpCommonSystem.postBegin(WorkstationItemsInGameHelpCommonSystem.java:83)
	at org.terasology.engine.modes.loadProcesses.PostBeginSystems.step(PostBeginSystems.java:44)
	at org.terasology.engine.modes.StateLoading.update(StateLoading.java:242)
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:413)
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:368)
	at org.terasology.engine.Terasology.main(Terasology.java:152)
```

The recipe that is processed in `InventoryInputProcessPartCommonSystem.getInputDescriptions` is ` WorkstationCrafting:RecipeStick`.

**Comment by Cervator** [comment] 2017-01-04 07:18
Just to verify: this still happens, with the full NeoTTA template running.

**Comment by aaron-harris** [comment] 2017-10-18 22:00
I wanted to take a crack at this, but can't reproduce the error (either with WorkstationCrafting alone, or with all of NeoTTA).  Is it possible that this has gotten fixed accidentally?

**Comment by Cervator** [comment] 2018-02-08 02:23
Hey @aaron-harris - sorry for missing that message for months :-) Yeah I just tried again, cannot replicate. Accidental fix ftw! Although I see another fix I had marked as maybe related, so that might be it. Closing!

**Closed as completed by Cervator** 2018-02-08 02:23 UTC
